export const initialFormState = {
  isImport: false,
  dailyTravelDistance: 35,
  comparisonDuration: "lifetime",
  evName: "",
  evInitialBuyingCost: null,
  motorPower: null,
  transportAndOtherCosts: null,
  claimedRange: null,
  batteryCapacity: 2.9,
  chargeCycle: 1500,
  perUnitElectricityCharge: 9.5,
  fuelVehicle: "petrol-2wheel",
  fuelVehicleName: "",
  fuelInitialBuyingCost: null,
  mileage: 35,
  servicingCost: 2000,
  servicingDuration: 2,
};
