export const initialFormState = {
  isImport: false,
  dailyTravelDistance: 35,
  comparisonDuration: "lifetime",
  evName: "",
  evInitialBuyingCost: null,
  motorPower: null,
  transportAndOtherCosts: null,
  claimedRange: null,
  batteryCapacity: null,
  batteryType: "Li-ion",
  chargeCycle:
    1500,
  perUnitElectricityCharge: 9.50,
  fuelVehicle: "Petrol (Bike / Scooter)",
  fuelVehicleName: "",
  fuelInitialBuyingCost: null,
  mileage: 35,
  servicingCost: 2000,
  servicingDuration: 2,
};
